---
version: "3.8"

services:
  django:
    environment:
      SERVER_ENVIRONMENT: test
  nginx:
    image: docker.io/nginx
    depends_on:
      - django
    volumes:
      - ./volumes/nginx/conf.d/prod:/etc/nginx/conf.d
      - ./app/staticfiles:/staticfiles:ro
    networks:
      - whiteboard
      - traefik-global-proxy
    expose:
      - "${PROJECT_PORT_EXTERNAL}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.${TEST_DOMAIN_NAME}`)"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=redirect-www-to-non-www@file"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt"
