# Generated by Django 4.0.4 on 2022-04-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_thing_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['-id']},
        ),
    ]
